{
 "title": "DORA Metrics Terraform",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Deployment Frequency day by day",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dora",
     "rawSql": "SELECT DATE_FORMAT(d.deploy_time, '%d-%m-%Y') AS day,\r\nCOUNT(*) AS nb_deployments\r\nFROM dora.deployments d\r\nWHERE $__timeFilter(d.deploy_time) \r\nGROUP BY day"
    }
   ]
  },
  {
   "title": "Deployment Frequency week by week",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dora",
     "rawSql": "SELECT DATE_FORMAT(d.deploy_time, '%Y-%u') AS week,\r\nCOUNT(*) AS nb_deployments\r\nFROM dora.deployments d\r\nWHERE $__timeFilter(d.deploy_time) -11\r\nGROUP BY week"
    }
   ]
  },
  {
   "title": "Lead Time",
   "type": "timeseries",
   "description": "Lead time en fonction du temps",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "dataset": "dora",
     "rawSql": "SELECT d.deploy_time, TIMESTAMPDIFF(minute, c.commit_time, d.deploy_time) AS LeadTime\r\nFROM dora.commits c\r\nJOIN dora.deployments d ON d.commit_id=c.commit_id"
    }
   ]
  },
  {
   "title": "Mean Time To Recovery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "dora",
     "rawSql": "SELECT d.deploy_time, TIMESTAMPDIFF(minute, i.incident_time, d.deploy_time) AS MTTR,\r\nAVG(TIMESTAMPDIFF(minute, i.incident_time, d.deploy_time)) OVER() AS AVG_MTTR\r\nFROM dora.deployments d \r\nJOIN dora.incidents i ON d.incident_id = i.id\r\nWHERE d.redeployment = TRUE AND $__timeFilter(d.deploy_time)"
    }
   ]
  },
  {
   "title": "Change Failure Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dora",
     "rawSql": "\tSELECT\r\n\t(SELECT COUNT(*) FROM incidents i WHERE $__timeFilter(i.incident_time)) / COUNT(*) AS FailureRate\r\n\tFROM \r\n\tdora.deployments d\r\nWHERE $__timeFilter(d.deploy_time)"
    }
   ]
  }
 ]
}